### ISSUE TITLE
Betting Lines for College Football Bowl Games

### ISSUE THREAD

**Issue by aqsmith08** [marcoblume/pinnacle.data#2]
Hi @marcoblume - I'm trying to find out if it's possible to get historical betting odds for college football bowl games. It'd be bowl games only from 2009 to present.

Note - I'm creating the issue here because it looks like the [Pinnacle API R Wrapper](https://github.com/marcoblume/pinnacle.API) only has "Pregame/Live Odds".

**Comment by marcoblume** [comment]
Hi

No that is not possible.





Marco Blume
Trading Director

[Pinnacle Logo]

marco.blume@pinnacle.com
www.pinnacle.com

[cid:image563cad.JPG@a70517b8.468a009c]

**Comment by aqsmith08** [comment]
Roger that. Thanks for your response.
